ACCELERATION_MAX = 30  # mm/s²
LINEAR_SPEED_MAX = 50  # mm/s
ADMITTED_POSITION_ERROR = 10  # mm

ROTATION_ACCELERATION_MAX = 0.8  # rad/s²
ROTATION_SPEED_MAX = 0.7  # rad/s
ADMITTED_ANGLE_ERROR = 0.05  # rad