ACCELERATION_MAX = 300  # mm/s²
LINEAR_SPEED_MAX = 350  # mm/s
ADMITTED_POSITION_ERROR = 5  # mm

ROTATION_ACCELERATION_MAX = 1.0 # rad/s²
ROTATION_SPEED_MAX = 0.9  # rad/s
ADMITTED_ANGLE_ERROR = 0.05  # rad

### Position control
LOOKAHEAD_DISTANCE = 200.